-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(P.PRICE * OS.SALES_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCT P join OFFLINE_SALE OS on P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY p.product_code
order by TOTAL_REVENUE DESC, PRODUCT_CODE ASC